### ISSUE TITLE
KeyError: tensor(259)

### ISSUE THREAD

**Issue by LeelaSravani** [LianHaiMiao/Attentive-Group-Recommendation#11]
In main.py:

    def grp_forward(self, group_inputs, item_inputs):
        group_embeds = Variable(torch.Tensor())
        item_embeds_full = self.itemembeds(Variable(torch.LongTensor(item_inputs)))
        for i, j in zip(group_inputs, item_inputs):
            members = self.group_member_dict[i]   ## Showing Error here
            members_embeds = self.userembeds(Variable(torch.LongTensor(members)))

Error:

AGREE at embedding size 32, run Iteration:30, NDCG and HR at 5
E:\Anaconda3\lib\site-packages\torch\nn\functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Iteration 0, loss is [0.9998 ]
Traceback (most recent call last):
  File "C:/Users/Leela Sravani/Desktop/RECO PAPERS/Attentive-Group-Recommendation-master/main.py", line 103, in <module>
    training(agree, dataset.get_group_dataloader(config.batch_size), epoch, config, 'group')
  File "C:/Users/Leela Sravani/Desktop/RECO PAPERS/Attentive-Group-Recommendation-master/main.py", line 50, in training
    pos_prediction = model(user_input, None, pos_item_input)
  File "E:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Leela Sravani\Desktop\RECO PAPERS\Attentive-Group-Recommendation-master\model\agree.py", line 34, in forward
    out = self.grp_forward(group_inputs, item_inputs)
  File "C:\Users\Leela Sravani\Desktop\RECO PAPERS\Attentive-Group-Recommendation-master\model\agree.py", line 47, in grp_forward
    members = self.group_member_dict[i]
KeyError: tensor(259)

Process finished with exit code 1

Kindly help solving this..

**Comment by zanshuxun** [comment]
During the data process stage, the keys of `group_member_dict` is integers. So we need to converts the tensor to standard Python integer number:
`members = self.group_member_dict[i.item()]`
